### ISSUE TITLE
Minecraft Game keeps on crashing. 

### ISSUE THREAD

**Issue by Jonathaan44** [Changeling-Gaming/Dragonspire-Reborn-Avali#1]
Don't really understand why I keep on crashing just opening my inventory. 

https://paste.ee/p/0p4bF

Thanks!

**Comment by Aaronstar-McClure** [comment]
At a glance, it looks like minecraft is crashing when trying to render an immersive rail, either in your inventory or in jei.
I'll try hopping on to see if I can invsee your inventory to see if you have one of them and I can try removing it temporarly.

**Comment by Aaronstar-McClure** [comment]
@Jonathaan44 could you ping me on discord please? i need to know when you are on the server so i can invsee.

**Comment by Jonathaan44** [comment]
Yes I'll ping you on discord. My username is @Jonathaan44 but yes

**Comment by Aaronstar-McClure** [comment]
jei was funky. maybe because of multimc?
