### ISSUE TITLE
Servers is saying its down

### ISSUE THREAD

**Issue by NeoTheW0lf** [Changeling-Gaming/Dragonspire-Reborn-Avali#11]
Server won't let me connect and MC is telling me it is down. I have used the right IP and I am using the most recent modpack version so I don't know whats wrong

**Comment by NeoTheW0lf** [comment]
![Capture](https://user-images.githubusercontent.com/97362900/148658854-7704f077-71bb-4860-b522-41e06d9068ea.PNG)

**Comment by Aaronstar-McClure** [comment]
The server is currently unavailable do to lack of payment.

**Comment by NeoTheW0lf** [comment]
Ah ok

**Comment by NeoTheW0lf** [comment]
Makes sense
