### ISSUE TITLE
Failed to connect

### ISSUE THREAD

**Issue by aRandomPerson0** [Changeling-Gaming/Dragonspire-Reborn-Avali#12]
it says: "Internal Exception: java.lang.IndexOutOfBoundsException: readerIndex(42) + length(1) exceeds writerIndex(42): PooledUnsafeDirectByteBuf(ridx: 42, widx: 42, cap: 42)"

[latest.log](https://github.com/Changeling-Gaming/Dragonspire-Reborn-Avali/files/7860701/latest.log)

**Comment by AftDawn** [comment]
Hi, from a quick look at the provided logs, the error doesn't seem to be logged, but i am seeing Immersive Railroad errors near the end of the logs, it may be that?

**Comment by Nyinxie** [comment]
are you using Optifine?

**Comment by aRandomPerson0** [comment]
> are you using Optifine?

Not with this modpack

**Comment by aRandomPerson0** [comment]
Deleting and reinstalling the modpack fixed it
