### ISSUE TITLE
modpack not installing and working

### ISSUE THREAD

**Issue by Neszumi** [Changeling-Gaming/Dragonspire-Reborn-Avali#13]
I get a error every time I try to install the modpack on the curseforge app and when I download the file from the website and play the modpack I get a error that says:

The game crashed whilst initializing game
Error: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
Exit Code: -1

also I'm installing: Dragonspire Reborn The Return of the Avali-2.3.2.zip

**Comment by Nyinxie** [comment]
> I get a error every time I try to install the modpack on the curseforge app and when I download the file from the website and play the modpack I get a error that says:
> 
> The game crashed whilst initializing game Error: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered Exit Code: -1
> 
> also I'm installing: Dragonspire Reborn The Return of the Avali-2.3.2.zip

Just to check, have you tried uninstalling the pack, deleting the mincraft/curseforge folder

**Comment by Neszumi** [comment]
it worked. i had to uninstall and reinstall curseforge
