### ISSUE TITLE
Custom player models breaking

### ISSUE THREAD

**Issue by OverlordAvali** [Changeling-Gaming/Dragonspire-Reborn-Avali#2]
For some reason something is causing the custom player models to break as they would change us back to our default skin even if we exported our model correctly and it seems to be happening to random people at random times. I would recommend looking into this.

**Comment by Nyinxie** [comment]
> For some reason something is causing the custom player models to break as they would change us back to our default skin even if we exported our model correctly and it seems to be happening to random people at random times. I would recommend looking into this.

need a bit more than just text m8
